/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-05-23 04:24:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>UMS</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        html,body\r\n");
      out.write("            {\r\n");
      out.write("                box-sizing: border-box;\r\n");
      out.write("                overflow-x: hidden;\r\n");
      out.write("            }\r\n");
      out.write("            header\r\n");
      out.write("            {\r\n");
      out.write("                background-image: url(lib.jpg);\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 800px;\r\n");
      out.write("            }\r\n");
      out.write("            body\r\n");
      out.write("            {\r\n");
      out.write("                position: relative;\r\n");
      out.write("            }\r\n");
      out.write("            body::before\r\n");
      out.write("            {\r\n");
      out.write("                content: \"\";\r\n");
      out.write("                background-image: url(headerimg.png);\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                top: 0;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("                opacity: 0.5;\r\n");
      out.write("                z-index: -1;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            header {\r\n");
      out.write("                background-image: url(lib.jpg);\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                height: 800px;\r\n");
      out.write("            }\r\n");
      out.write("            .custom-modal {\r\n");
      out.write("                position: relative;\r\n");
      out.write("                z-index: 1050;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-secondary\" data-bs-spy=\"scroll\" data-bs-target=\".navbar\">\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-dark p-2 fixed-top row align-items-center\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#c\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"#c\">\r\n");
      out.write("                <li class=\"nav-item col-2\"><i class=\"bi bi-list text-light\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#oc\" style=\"font-size: larger;\"></i></li>\r\n");
      out.write("                <ul class=\"navbar-nav nav-fill col-8\">\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link text-light\" href=\"#home\">Home</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link text-light\" href=\"#admissions\">Admissions</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link text-light\" href=\"#research\">Research</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link text-light\" href=\"#alumni\">Alumni</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link text-light\" href=\"#contact\">Contact</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <li class=\"nav-item col-2 d-flex justify-content-end px-5\"><i type=\"button\" class=\"bi bi-person-circle text-light float-right\" data-bs-toggle=\"modal\" data-bs-target=\"#signin\" style=\"font-size: larger;\"></i></li>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Offcanvas menu -->\r\n");
      out.write("    <div class=\"offcanvas offcanvas-start text-bg-dark\" id=\"oc\" style=\"--bs-bg-opacity: 0.9\">\r\n");
      out.write("        <div class=\"offcanvas-header\">\r\n");
      out.write("            <h2 class=\"offcanvas-title\">UMS</h2>\r\n");
      out.write("            <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"offcanvas\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"offcanvas-body\">\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-dark text-light col-11 p-3 m-3\">Students</a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/course/viewCourse\" type=\"button\" class=\"btn btn-dark text-light col-11 p-3 m-3\">Courses</a>\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-dark text-light col-11 p-3 m-3\">Enrollments</a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/faculty/viewFaculty\" type=\"button\" class=\"btn btn-dark text-light col-11 p-3 m-3\">Faculties</a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/department/viewDept\" type=\"submit\"  class=\"btn btn-dark text-light col-11 p-3 m-3\">Departments</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Modal for Signin -->\r\n");
      out.write("    <div class=\"modal modal-md fade bg-dark\" style=\"--bs-bg-opacity: 0.5\" id=\"signin\">\r\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered modal-dialog-scrollable\">\r\n");
      out.write("            <div class=\"modal-content modal-content-md text-bg-dark\" style=\"--bs-bg-opacity: 0.9\">\r\n");
      out.write("                <div class=\"modal-header text-light border-secondary\">\r\n");
      out.write("                    <h3 class=\"modal-title\">UMS</h3>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body border-secondary\">\r\n");
      out.write("                    <!-- Nav tabs -->\r\n");
      out.write("                    <ul class=\"nav nav-tabs\" id=\"loginTabs\" role=\"tablist\">\r\n");
      out.write("                        <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                            <button class=\"nav-link active\" id=\"login-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#login\" type=\"button\" role=\"tab\" aria-controls=\"login\" aria-selected=\"true\">Login</button>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                            <button class=\"nav-link\" id=\"signup-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#signup\" type=\"button\" role=\"tab\" aria-controls=\"signup\" aria-selected=\"false\">Sign Up</button>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- Tab panes -->\r\n");
      out.write("                    <div class=\"tab-content mt-3\">\r\n");
      out.write("                        <!-- Login Tab Content -->\r\n");
      out.write("                        <div class=\"tab-pane fade show active\" id=\"login\" role=\"tabpanel\" aria-labelledby=\"login-tab\">\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input type=\"email\" class=\"form-control border-secondary\" id=\"loginMail\" placeholder=\"Enter your Mail\" required>\r\n");
      out.write("                                <label for=\"loginMail\" class=\"form-label text-dark\">Email</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input type=\"password\" class=\"form-control border-secondary\" id=\"loginPwd\" placeholder=\"Enter your password\" required>\r\n");
      out.write("                                <label for=\"loginPwd\" class=\"form-label text-dark\">Password</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-check form-switch mb-3\">\r\n");
      out.write("                                <input class=\"form-check-input focus-ring\" type=\"checkbox\" id=\"loginSwitch\" name=\"remember\" value=\"yes\" checked style=\"--bs-focus-ring-color: rgba(var(--bs-warning-rgb), .25)\">\r\n");
      out.write("                                <label class=\"form-check-label\">Remember me</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-dark\" id=\"loginButton\">Login</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Signup Tab Content -->\r\n");
      out.write("                        <div class=\"tab-pane fade\" id=\"signup\" role=\"tabpanel\" aria-labelledby=\"signup-tab\">\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input type=\"email\" class=\"form-control border-secondary\" id=\"signupMail\" placeholder=\"Enter your Mail\" required>\r\n");
      out.write("                                <label for=\"signupMail\" class=\"form-label text-dark\">Email</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input type=\"password\" class=\"form-control border-secondary\" id=\"signupPwd\" placeholder=\"Enter your password\" required>\r\n");
      out.write("                                <label for=\"signupPwd\" class=\"form-label text-dark\">Password</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input type=\"password\" class=\"form-control border-secondary\" id=\"confirmPwd\" placeholder=\"Confirm password\" required>\r\n");
      out.write("                                <label for=\"confirmPwd\" class=\"form-label text-dark\">Confirm Password</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-dark\" id=\"signupButton\">Sign Up</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <header id=\"home\" class=\"d-flex align-items-center\">\r\n");
      out.write("        <div id=\"carouselExampleControls\" class=\"carousel slide col-8 m-3\" data-bs-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <img src='https://i.imgur.com/wJsns6a.jpeg' class=\"d-block w-100\" alt=\"University 1\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img src='https://i.imgur.com/hUA5TFW.jpeg' class=\"d-block w-100\" alt=\"University 2\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img src='https://i.imgur.com/A3hCpJK.jpeg' class=\"d-block w-100\" alt=\"University 3\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleControls\" data-bs-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleControls\" data-bs-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card border-dark bg-dark text-light p-3 col-3 m-3\" style=\"--bs-bg-opacity: 0.9\">\r\n");
      out.write("            <div class=\"card-header border-secondary\">\r\n");
      out.write("                <h2 style=\"text-transform: uppercase;\">Welcome to Our University</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <span></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-3 ps-4 m-3\">\r\n");
      out.write("            <button class=\"btn btn-lg custom-button col-10 m-2\"><span>Explore</span></button>\r\n");
      out.write("            <button class=\"btn btn-lg custom-button col-10 m-2\"><span>Admissions</span></button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>    \r\n");
      out.write("\r\n");
      out.write("    <div id=\"about\" class=\"container my-4 rounded d-flex justify-content-center\">\r\n");
      out.write("        <div class=\"card bg-black text-light p-3 col-12\" style=\"--bs-bg-opacity: 0.8\">\r\n");
      out.write("            <div class=\"card-header border-secondary\">\r\n");
      out.write("                <h1>About Our University</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <p>Welcome to our university! We're dedicated to fostering an environment of academic excellence, innovation, and personal growth.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h3>Our Mission</h3>\r\n");
      out.write("                <p>Our mission is to provide quality education that empowers individuals to reach their full potential and contribute positively to society.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h3>Academic Excellence</h3>\r\n");
      out.write("                <p>We pride ourselves on our rigorous academic programs designed to challenge and inspire students. Our distinguished faculty are leaders in their fields, and our modern facilities provide an ideal environment for learning and research.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h3>Student-Centered Approach</h3>\r\n");
      out.write("                <p>At our university, students come first. We offer a supportive and inclusive community where every student is valued and encouraged to pursue their passions. Our comprehensive student services ensure that each individual receives the guidance and support they need to succeed.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h3>Global Perspective</h3>\r\n");
      out.write("                <p>We embrace diversity and foster a global perspective in all aspects of our university experience. Our international programs, partnerships, and exchange opportunities prepare students to thrive in an interconnected world.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h3>Community Engagement</h3>\r\n");
      out.write("                <p>As an integral part of our local and global communities, we are committed to making a positive impact through service, research, and outreach. Our students, faculty, and staff actively contribute to solving real-world problems and improving lives.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("        <!-- Academics Card -->\r\n");
      out.write("        <div id=\"academics\" class=\"col-md-5 my-4\">\r\n");
      out.write("            <div class=\"card border-dark bg-dark text-light p-3\" style=\"--bs-bg-opacity: 0.8\">\r\n");
      out.write("                <div class=\"card-header border-black\">\r\n");
      out.write("                    <h1>Academics</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <p>Our university offers a wide range of academic programs designed to meet the diverse interests and career goals of our students. Explore our departments and programs:</p>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>Arts & Humanities</li>\r\n");
      out.write("                        <li>Business & Economics</li>\r\n");
      out.write("                        <li>Engineering</li>\r\n");
      out.write("                        <li>Health Sciences</li>\r\n");
      out.write("                        <li>Science & Technology</li>\r\n");
      out.write("                        <li>Law</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-footer\">\r\n");
      out.write("                    <a href=\"#contact\" class=\"btn btn-dark\">Contact Academics</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        <!-- Admissions Card -->\r\n");
      out.write("        <div id=\"admissions\" class=\"col-md-5 my-4\">\r\n");
      out.write("            <div class=\"card border-dark bg-dark text-light p-3\" style=\"--bs-bg-opacity: 0.8\">\r\n");
      out.write("                <div class=\"card-header border-black\">\r\n");
      out.write("                    <h1>Admissions</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <p>Thank you for considering our university for your academic journey. Here's some information about our admission process:</p>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>Explore our academic programs to find the one that suits your interests and goals.</li>\r\n");
      out.write("                        <li>Review the admission requirements for your chosen program.</li>\r\n");
      out.write("                        <li>Complete the online application form.</li>\r\n");
      out.write("                        <li>Wait for notification of your admission status.</li>\r\n");
      out.write("                        <li>Upon acceptance, follow the instructions to enroll in your chosen program.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-footer\">\r\n");
      out.write("                    <a href=\"#contact\" class=\"btn btn-dark\">Contact Admissions</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("    <div id=\"research\" class=\"container my-4 rounded\">\r\n");
      out.write("        <div class=\"card bg-black text-light col-8 mx-auto p-3\" style=\"--bs-bg-opacity: 0.8\">\r\n");
      out.write("            <div class=\"card-header border-secondary\">\r\n");
      out.write("                <h1>Research</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <p>Research is a vital component of our university's mission, driving innovation and discovery in various fields.</p>\r\n");
      out.write("                <p>Our faculty and students engage in groundbreaking research projects, contributing to advancements in:</p>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>Biotechnology and Life Sciences</li>\r\n");
      out.write("                    <li>Computer Science and Information Technology</li>\r\n");
      out.write("                    <li>Environmental Studies</li>\r\n");
      out.write("                    <li>Medicine and Health</li>\r\n");
      out.write("                    <li>Social Sciences</li>\r\n");
      out.write("                    <li>Engineering</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p>Through collaborative efforts and state-of-the-art facilities, we aim to address complex global challenges and make a positive impact on society.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>    \r\n");
      out.write("    \r\n");
      out.write("    <div id=\"alumni\" class=\"container my-4 rounded d-flex justify-content-center\">\r\n");
      out.write("        <div class=\"card row bg-dark text-light p-3 col-8 \" style=\"--bs-bg-opacity: 0.8\">\r\n");
      out.write("            <div class=\"card-header m-2 border-black d-flex justify-content-center\">\r\n");
      out.write("                <h3>Our Alumni</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body row justify-content-center\">\r\n");
      out.write("                <div class=\"card border-success text-bg-dark col-2 ms-4 p-3 align-items-center\">\r\n");
      out.write("                    <div class=\"card-img-top\"><img src=\"alumni1.jpg\" width=\"135px\"></div>\r\n");
      out.write("                    <div class=\"card-header border-success\">John Doe</div>\r\n");
      out.write("                    <div class=\"card-footer\">\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-primary\">LinkedIn</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card border-info text-bg-dark col-2 ms-4 p-3 align-items-center\">\r\n");
      out.write("                    <div class=\"card-img-top\"><img src=\"alumni2.jpg\" width=\"135px\"></div>\r\n");
      out.write("                    <div class=\"card-header border-info\">Jane Smith</div>\r\n");
      out.write("                    <div class=\"card-footer\">\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-primary\">LinkedIn</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card border-info text-bg-dark col-2 ms-4 p-3 align-items-center\">\r\n");
      out.write("                    <div class=\"card-img-top\"><img src=\"alumni3.jpg\" width=\"135px\"></div>\r\n");
      out.write("                    <div class=\"card-header border-info\">Michael Johnson</div>\r\n");
      out.write("                    <div class=\"card-footer\">\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-primary\">LinkedIn</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card border-info text-bg-dark col-2 ms-4 p-3 align-items-center\">\r\n");
      out.write("                    <div class=\"card-img-top\"><img src=\"alumni4.jpg\" width=\"135px\"></div>\r\n");
      out.write("                    <div class=\"card-header border-info\">Emily Davis</div>\r\n");
      out.write("                    <div class=\"card-footer\">\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-primary\">LinkedIn</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div id=\"contact\" class=\"my-4 rounded row d-flex justify-content-center\">\r\n");
      out.write("        <div class=\"card bg-black text-white col-6 text-center\" style=\"--bs-bg-opacity: 0.8\">\r\n");
      out.write("            <div class=\"card-header border-secondary\"><h1>Contact Us</h1></div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <form class=\"form text-dark\">\r\n");
      out.write("                    <div class=\"input-group mb-3\">\r\n");
      out.write("                        <div class=\"form-floating\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"Enter your name\" required>\r\n");
      out.write("                            <label for=\"name\" class=\"form-label\">First Name</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-floating\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"Enter your name\">\r\n");
      out.write("                            <label for=\"name\" class=\"form-label\">Last Name</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-floating mb-3\">\r\n");
      out.write("                        <input type=\"email\" class=\"form-control\" id=\"mail\" placeholder=\"Enter your Mail\" required>\r\n");
      out.write("                        <label for=\"mail\" class=\"form-label\">Email</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-floating mb-3\">\r\n");
      out.write("                        <textarea class=\"form-control\" placeholder=\"Leave a comment here\" id=\"msg\" style=\"height: 100px;\"></textarea>\r\n");
      out.write("                        <label for=\"msg\" class=\"form-label\">Comments</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-outline-secondary\">Send</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"bg-dark text-light py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <h5>Quick Links</h5>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"#home\" class=\"text-light\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"#about\" class=\"text-light\">About Us</a></li>\r\n");
      out.write("                        <li><a href=\"#academics\" class=\"text-light\">Academics</a></li>\r\n");
      out.write("                        <li><a href=\"#research\" class=\"text-light\">Research</a></li>\r\n");
      out.write("                        <li><a href=\"#contact\" class=\"text-light\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <h5>Contact Information</h5>\r\n");
      out.write("                    <p>123 University Street, City, Country</p>\r\n");
      out.write("                    <p>Email: info@university.edu</p>\r\n");
      out.write("                    <p>Phone: +123 456 7890</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"bg-light\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <p class=\"text-muted\">&copy; 2024 University. All rights reserved.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-end\">\r\n");
      out.write("                    <ul class=\"list-inline\">\r\n");
      out.write("                        <li class=\"list-inline-item\"><a href=\"#\" class=\"text-light\">Terms of Use</a></li>\r\n");
      out.write("                        <li class=\"list-inline-item\"><a href=\"#\" class=\"text-light\">Privacy Policy</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("	<!-- Faculty Modal -->\r\n");
      out.write("	<div class=\"modal fade bg-dark\" id=\"facultyModal\">\r\n");
      out.write("        <div class=\"modal-dialog modal-fullscreen modal-dialog-centered\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("	            <div class=\"modal-header\">\r\n");
      out.write("	                <h5 class=\"modal-title col-11\" id=\"facultyModalLabel\">Faculties</h5>\r\n");
      out.write("	                <a type=\"button\" class=\"btn btn-success\" data-bs-toggle=\"modal\" aria-label=\"Insert\">Insert</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("	                <!-- Table to display faculties -->\r\n");
      out.write("	                \r\n");
      out.write("	                <table class=\"table table-striped\">\r\n");
      out.write("	                    <thead>\r\n");
      out.write("	                        <tr>\r\n");
      out.write("	                            <th>ID</th>\r\n");
      out.write("                                <th>Name</th>\r\n");
      out.write("	                            <th>Department ID</th>\r\n");
      out.write("                                <th></th>\r\n");
      out.write("	                        </tr>\r\n");
      out.write("	                    </thead>\r\n");
      out.write("	                    <tbody>\r\n");
      out.write("	                        <!-- Iterate over faculties and display them -->\r\n");
      out.write("	                        <c:forEach items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${faculties}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" var=\"faculty\">\r\n");
      out.write("	                            <tr>\r\n");
      out.write("	                                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${faculty.facultyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("	                                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${faculty.facultyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("	                                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${faculty.deptId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                                    <td><button type=\"button\" class=\"btn btn-primary\"><i class=\"bi bi-pencil-square\"></i></button></td>\r\n");
      out.write("                                    <td><button type=\"button\" class=\"btn btn-danger\"><i class=\"bi bi-trash3\"></i></button></td>\r\n");
      out.write("	                            </tr>\r\n");
      out.write("	                        </c:forEach>\r\n");
      out.write("	                    </tbody>\r\n");
      out.write("	                </table>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"modal-footer\">\r\n");
      out.write("	                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("	            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("   \r\n");
      out.write("    <!-- Course Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"courseModal\" tabindex=\"-1\" aria-labelledby=\"courseModalLabel\" data-bs-backdrop=\"static\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-fullscreen modal-dialog-centered\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title col-11\" id=\"courseModalLabel\">Courses</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-success\" data-bs-toggle=\"modal\" aria-label=\"Insert\">Insert</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <!-- Table to display courses -->\r\n");
      out.write("                    <table class=\"table table-striped\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>ID</th>\r\n");
      out.write("                                <th>Name</th>\r\n");
      out.write("                                <th>Department ID</th>\r\n");
      out.write("                                <th>Faculty ID</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <!-- Iterate over courses and display them -->\r\n");
      out.write("                            <c:forEach items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courses}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" var=\"course\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.courseId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.courseName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.deptId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.facultyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                                    <td><button type=\"button\" class=\"btn btn-primary\"><i class=\"bi bi-pencil-square\"></i></button></td>\r\n");
      out.write("                                    <td><button type=\"button\" class=\"btn btn-danger\"><i class=\"bi bi-trash3\"></i></button></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </c:forEach>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
